### ISSUE TITLE
Raise error when run examples

### ISSUE THREAD

**Issue by yyydido** [NifTK/NiftyNet#16]
First, I used net_download to download the example data.Then, I want to try these examples
[https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer/blob/master/anisotropic_nets_brats_challenge_model_zoo.md](url)
`net_run inference -a anisotropic_nets_brats_challenge.brats_seg_app.BRATSApp -c extensions/anisotropic_nets_brats_challenge/whole_tumor_axial.ini `

`NiftyNet version 0.2.0.post1
Traceback (most recent call last):
  File "/usr/local/bin/net_run", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/niftynet/__init__.py", line 33, in main
    system_param, input_data_param = user_parameters_parser.run()
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/user_parameters_parser.py", line 75, in run
    app_module = ApplicationFactory.create(module_name)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 155, in create
    return select_module(name, cls.type_str, cls.SUPPORTED)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 117, in select_module
    the_module = getattr(importlib.import_module(module), class_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'anisotropic_nets_brats_challenge'
`

[https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer/blob/master/highres3dnet_brain_parcellation_model_zoo.md](url)
`net_run inference -c extensions/highres3dnet_brain_parcellation/highres3dnet_config_eval.ini`
`NiftyNet version 0.2.0.post1
CRITICAL:tensorflow:Could not import application: Incorrect module name format . Expected "module.object".
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 116, in select_module
    module, class_name = module_name.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/user_parameters_parser.py", line 75, in run
    app_module = ApplicationFactory.create(module_name)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 155, in create
    return select_module(name, cls.type_str, cls.SUPPORTED)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 136, in select_module
    raise ValueError(err)
ValueError: Could not import application: Incorrect module name format . Expected "module.object".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/net_run", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/niftynet/__init__.py", line 33, in main
    system_param, input_data_param = user_parameters_parser.run()
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/user_parameters_parser.py", line 83, in run
    module_name, app_module.REQUIRED_CONFIG_SECTION))
UnboundLocalError: local variable 'app_module' referenced before assignment
`

[https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer/blob/master/ultrasound_simulator_gan_model_zoo.md](url)
`net_run inference -c extensions/ultrasound_simulator_gan/config.ini`
`NiftyNet version 0.2.0.post1
CRITICAL:tensorflow:Could not import application: Incorrect module name format . Expected "module.object".
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 116, in select_module
    module, class_name = module_name.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/user_parameters_parser.py", line 75, in run
    app_module = ApplicationFactory.create(module_name)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 155, in create
    return select_module(name, cls.type_str, cls.SUPPORTED)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 136, in select_module
    raise ValueError(err)
ValueError: Could not import application: Incorrect module name format . Expected "module.object".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/net_run", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/niftynet/__init__.py", line 33, in main
    system_param, input_data_param = user_parameters_parser.run()
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/user_parameters_parser.py", line 83, in run
    module_name, app_module.REQUIRED_CONFIG_SECTION))
UnboundLocalError: local variable 'app_module' referenced before assignment
`

**Comment by wyli** [comment]
Hi @yyydido at the moment the pip version is slightly out-of-date, the next release is coming soon.
In the meanwhile, you could clone the source repo directory and use command `python net_download.py`, `python net_run.py` instead -- please feel free to reopen the issue if the error persists.
