### ISSUE TITLE
Inference Error: TypeError: layer_op() got an unexpected keyword argument 'keep_prob'

### ISSUE THREAD

**Issue by EdwardMa12593** [NifTK/NiftyNet#163]
In the inference phase (segmentation application), my code keeps giving me this error: 
`layer_op() got an unexpected keyword argument 'keep_prob'`

Following is the detailed error:
```python
2018-07-21 15:09:54.633758: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/device:GPU:0 with 3084 MB memory) -> physical GPU (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File ".\net_segment.py", line 8, in <module>
    sys.exit(main())
  File "E:\DLCode\NiftyNet0708\niftynet\__init__.py", line 139, in main
    app_driver.run_application()
  File "E:\DLCode\NiftyNet0708\niftynet\engine\application_driver.py", line 255, in run_application
    self.graph = self._create_graph(self.graph)
  File "E:\DLCode\NiftyNet0708\niftynet\engine\application_driver.py", line 331, in _create_graph
    self.gradients_collector)
  File "E:\DLCode\NiftyNet0708\niftynet\application\segmentation_application.py", line 372, in connect_data_and_network
    net_out = self.net(image, **net_args)
  File "E:\DLCode\NiftyNet0708\niftynet\layer\base_layer.py", line 34, in __call__
    return self._op(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 455, in __call__
    result = self._call_func(args, kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
TypeError: layer_op() got an unexpected keyword argument 'keep_prob'

originally defined at:
  File "E:\DLCode\NiftyNet0708\niftynet\engine\application_driver.py", line 317, in _create_graph
    self.app.initialise_network()
  File "E:\DLCode\NiftyNet0708\niftynet\application\segmentation_application.py", line 282, in initialise_network
    acti_func=self.net_param.activation_function)
  File "E:\DLCode\NiftyNet0708\niftynet\network\downdilatednet.py", line 34, in __init__
    name=name)
  File "E:\DLCode\NiftyNet0708\niftynet\network\base_net.py", line 21, in __init__
    super(BaseNet, self).__init__(name=name)
  File "E:\DLCode\NiftyNet0708\niftynet\layer\base_layer.py", line 58, in __init__
    super(TrainableLayer, self).__init__(name=name)
  File "E:\DLCode\NiftyNet0708\niftynet\layer\base_layer.py", line 26, in __init__
    self._op = tf.make_template(name, self.layer_op, create_scope_now_=True)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 153, in make_template
    **kwargs)
```

Would it be possible for you to give me some advice to solve this problem.
Looking forward to your reply.

**Comment by wyli** [comment]
Hi @EdwardMa12593 is this related to https://github.com/NifTK/NiftyNet/issues/123#issuecomment-396998975?
