### ISSUE TITLE
raise error when run demo

### ISSUE THREAD

**Issue by yyydido** [NifTK/NiftyNet#21]
I run the demo net_segment for inference ,that's OK,but raise error when train :
`net_segment train -c ./extensions/dense_vnet_abdominal_ct/config.ini`

`Traceback (most recent call last):
  File "/usr/local/bin/net_segment", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/niftynet/__init__.py", line 54, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_driver.py", line 131, in initialise_application
    self.app.initialise_dataset_loader(data_param, app_param)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/application/segmentation_application.py", line 63, in initialise_dataset_loader
    self.reader.initialise_reader(data_param, task_param)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/io/image_reader.py", line 98, in initialise_reader
    self._file_list = util_csv.load_and_merge_csv_files(data_to_load)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/util_csv.py", line 254, in load_and_merge_csv_files
    match_and_write_filenames_to_csv([matcher], csv_file)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/util_csv.py", line 209, in match_and_write_filenames_to_csv
    KeywordsMatching.matching_subjects_and_filenames(c)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/filename_matching.py", line 73, in matching_subjects_and_filenames
    self.__dict__))
OSError: no file matched based on this matcher: {'filename_not_contains': (), 'filename_contains': ('Label',), 'path_to_search': ('/home/yyydido/niftynet/data/dense_vnet_abdominal_ct',)}'

**Comment by wyli** [comment]
Hi @yyydido the ground truth labels are not included in the model zoo at the moment, please have a look at the promise12 demo for more information on training a network (https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/tree/dev/demos/PROMISE12)

**Comment by yyydido** [comment]
Thanks, I got it. But I try this [https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/tree/dev/demos/BRATS17](url) that contains label，I  placed brats_segmentation.py and anisotropic_nets
on the $PYTHONPATH of the system environment,however,raise error ：

`net_run train -c ./extensions/anisotropic_nets_brats_challenge/whole_tumor_sagittal.ini -a brats_seg_app.BRATSApp --name anisotropic_nets.wt_net.WTNet
`

`NiftyNet version 0.2.1
CRITICAL:niftynet: ImportError("No module named 'brats_seg_app'",)
CRITICAL:niftynet: application: Could not import object"BRATSApp" from "brats_seg_app"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 153, in select_module
    the_module = importlib.import_module(module_str)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'brats_seg_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/net_run", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/niftynet/__init__.py", line 52, in main
    system_param, input_data_param = user_parameters_parser.run()
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/user_parameters_parser.py", line 108, in run
    app_module = ApplicationFactory.create(module_name)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 197, in create
    return select_module(name, cls.type_str, cls.SUPPORTED)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 182, in select_module
    raise ValueError(err)
ValueError: application: Could not import object"BRATSApp" from "brats_seg_app"
`

**Comment by wyli** [comment]
Hi @yyydido no problem, and for the BRATS demo it's also available in the model zoo (https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer/blob/master/anisotropic_nets_brats_challenge_model_zoo.md) `net_download` command would download the modules to `~/niftynet/extensions/anisotropic_nets_brats_challenge` by default. Perhaps this is easier to use.

Sorry for suggesting links in `demo` and `model zoo` back and forth, we've been migrating demos to the model zoo, documentation will be improved soon.

**Comment by yyydido** [comment]
Thanks for your reply,I am new in DL and thanks for your guide  again.

**Comment by yyydido** [comment]
Hi @wyli  I'll bother you again.
Now,I try [https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/tree/dev/demos/BRATS17](url) **for train not inference**.
First, this is my structure:
/home/yyydido/niftynet/
![tree](https://user-images.githubusercontent.com/26373884/34188805-31ea7838-e573-11e7-9e6a-95c5a524e7af.png)

Second,I added the directory /home/yyydido/niftynet/ on the PYTHONPATH of system environment:
export PYTHONPATH=/home/yyydido/niftynet:$PYTHONPATH

Thirdly,net_run at /home/yyydido/niftynet/ like this:
`net_run train -c ./extensions/anisotropic_nets_brats_challenge/whole_tumor_sagittal.ini -a brats_seg_app.BRATSApp --name anisotropic_nets.wt_net.WTNet`

The last,raise error:
`NiftyNet version 0.2.1
CRITICAL:niftynet: ImportError("No module named 'brats_seg_app'",)
CRITICAL:niftynet: application: Could not import object"BRATSApp" from "brats_seg_app"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 153, in select_module
    the_module = importlib.import_module(module_str)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'brats_seg_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/net_run", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/niftynet/__init__.py", line 52, in main
    system_param, input_data_param = user_parameters_parser.run()
  File "/usr/local/lib/python3.5/dist-packages/niftynet/utilities/user_parameters_parser.py", line 108, in run
    app_module = ApplicationFactory.create(module_name)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 197, in create
    return select_module(name, cls.type_str, cls.SUPPORTED)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_factory.py", line 182, in select_module
    raise ValueError(err)
ValueError: application: Could not import object"BRATSApp" from "brats_seg_app"
`
Could you help me find the cause of the error? Tanks a lot

**Comment by yyydido** [comment]
I have solved above problem.
