### ISSUE TITLE
InvalidArgumentError Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape when traing network using niftynet

### ISSUE THREAD

**Issue by shieldlance** [NifTK/NiftyNet#215]
I'm training a segment network using my data, but I got the following errors:

python-traceback
INFO:niftynet: SegmentationApplication stopped (time in second 11.50). Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1327, in _do_call return fn(*args) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1312, in _run_fn options, feed_dict, fetch_list, target_list, run_metadata) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun status, run_metadata) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in exit c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.InvalidArgumentError: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
[[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/SparseReshape, worker_0/loss_function/ones_like, worker_0/loss_function/SparseReshape:1, worker_0/loss_function/Softmax)]] [[Node: worker_0/loss_function/truediv/_37 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1503_worker_0/loss_function/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "/usr/local/bin/net_segment", line 11, in sys.exit(main()) File "/usr/local/lib/python3.5/dist-packages/niftynet/init.py", line 139, in main app_driver.run_application() File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_driver.py", line 272, in run_application self._training_loop(session, loop_status) File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_driver.py", line 471, in _training_loop self._loop(self.interleaved_iteration_generator(), sess, loop_status) File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_driver.py", line 439, in _loop feed_dict=iter_msg.data_feed_dict) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 905, in run run_metadata_ptr) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1140, in _run feed_dict_tensor, options, run_metadata) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run run_metadata) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call raise type(e)(node_def, op, message) tensorflow.python.framework.errors_impl.InvalidArgumentError: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
[[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/SparseReshape, worker_0/loss_function/ones_like, worker_0/loss_function/SparseReshape:1, worker_0/loss_function/Softmax)]] [[Node: worker_0/loss_function/truediv/_37 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1503_worker_0/loss_function/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]

Caused by op 'worker_0/loss_function/mul', defined at: File "/usr/local/bin/net_segment", line 11, in sys.exit(main()) File "/usr/local/lib/python3.5/dist-packages/niftynet/init.py", line 139, in main app_driver.run_application() File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_driver.py", line 255, in run_application self.graph = self._create_graph(self.graph) File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/application_driver.py", line 331, in _create_graph self.gradients_collector) File "/usr/local/lib/python3.5/dist-packages/niftynet/application/segmentation_application.py", line 324, in connect_data_and_network weight_map=data_dict.get('weight', None)) File "/usr/local/lib/python3.5/dist-packages/niftynet/layer/base_layer.py", line 34, in call return self._op(*args, **kwargs) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 455, in call result = self._call_func(args, kwargs) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 406, in _call_func result = self._func(*args, **kwargs) File "/usr/local/lib/python3.5/dist-packages/niftynet/layer/loss_segmentation.py", line 114, in layer_op loss_batch.append(self._data_loss_func(**loss_params)) File "/usr/local/lib/python3.5/dist-packages/niftynet/layer/loss_segmentation.py", line 411, in dice one_hot * prediction, reduction_axes=[0]) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 982, in binary_op_wrapper_sparse name=name), sp_x.dense_shape) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_sparse_ops.py", line 1331, in sparse_dense_cwise_mul sp_shape=sp_shape, dense=dense, name=name) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper op_def=op_def) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3290, in create_op op_def=op_def) File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1654, in init self._traceback = self._graph._extract_stack() # pylint: disable=protected- acess

InvalidArgumentError (see above for traceback): Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/SparseReshape, worker_0/loss_function/ones_like, worker_0/loss_function/SparseReshape:1, worker_0/loss_function/Softmax)]] [[Node: worker_0/loss_function/truediv/_37 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1503_worker_0/loss_function/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]

And the config:

```
[Fimage]
csv_file=
path_to_search = /home/zliang/demo/segheart/data/
filename_contains = F,img
filename_not_contains =
spatial_window_size = (64, 64, 64)
#interp_order = 0
pixdim=(1.0, 1.0, 1.0)
axcodes=(A, R, S)

[label]
path_to_search =  /home/zliang/demo/segheart/data/
filename_contains = F
filename_not_contains =img
spatial_window_size = (64, 64, 64)
interp_order = 0
pixdim=(1.0, 1.0, 1.0)
axcodes=( A, R, S)

############################## system configuration sections
[SYSTEM]
cuda_devices = ""
num_threads = 2
num_gpus = 1
model_dir = ./models/model_segheart_highres3d

[NETWORK]
name = highres3dnet
activation_function = relu
batch_size = 2
decay = 0
reg_type = L2


window_sampling=resize




[TRAINING]
lr = 0.001
loss_type = Dice
starting_iter = 0
save_every_n = 50
max_iter = 10000
max_checkpoints = 200

[INFERENCE]
save_seg_dir = ./output/highres3d
output_interp_order = 0
spatial_window_size = (96, 96, 96)

[EVALUATION]
evaluations=Dice
save_csv_dir=./evaluation
evaluation_units=label

############################ custom configuration sections
[SEGMENTATION]
image = Fimage
label = label
output_prob = False

num_classes = 40
```
I have read some answers like #7, and tried the methods, but the issue still can't be solved.

Any help would be appreciated.

**Comment by shieldlance** [comment]
refering #8
