### ISSUE TITLE
"IndexError: pop from empty list " during training of segmentation application

### ISSUE THREAD

**Issue by JunMa11** [NifTK/NiftyNet#238]
Firstly, thanks for the excellent work!

When using the segmentation application, of the top 6032 iterations, everything is well. 
However, a strange error occurred in the next iteration: IndexError: pop from empty list.
I have checked the nii training data, they are all well.
Any suggestions about this problem would be very much appreciated.

Following is the detailed error information.
```python-traceback
[1mINFO:niftynet:[0m Training iter 6033, loss=0.1859075427055359 (0.937950s)
D:\ProgramData\Anaconda3\lib\site-packages\nibabel\nifti1.py:582: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ext_def = np.fromstring(ext_def, dtype=np.int32)
D:\ProgramData\Anaconda3\lib\site-packages\nibabel\nifti1.py:582: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ext_def = np.fromstring(ext_def, dtype=np.int32)
D:\ProgramData\Anaconda3\lib\site-packages\nibabel\nifti1.py:582: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ext_def = np.fromstring(ext_def, dtype=np.int32)
D:\ProgramData\Anaconda3\lib\site-packages\nibabel\nifti1.py:582: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ext_def = np.fromstring(ext_def, dtype=np.int32)
D:\ProgramData\Anaconda3\lib\site-packages\nibabel\nifti1.py:582: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ext_def = np.fromstring(ext_def, dtype=np.int32)
D:\ProgramData\Anaconda3\lib\site-packages\scipy\ndimage\interpolation.py:583: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
Traceback (most recent call last):
  File "F:\DLCode\NiftyNet0708\niftynet\engine\image_window_buffer.py", line 148, in _push
    for output_dict in self():
  File "F:\DLCode\NiftyNet0708\niftynet\engine\sampler_resize.py", line 73, in layer_op
    image_id, data, interp_orders = self.reader(shuffle=self.shuffle)
  File "F:\DLCode\NiftyNet0708\niftynet\layer\base_layer.py", line 34, in __call__
    return self._op(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 455, in __call__
    result = self._call_func(args, kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 400, in _call_func
    result = self._func(*args, **kwargs)
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_reader.py", line 230, in layer_op
    {field: image.get_data() for (field, image) in image_dict.items()}
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_reader.py", line 230, in <dictcomp>
    {field: image.get_data() for (field, image) in image_dict.items()}
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_type.py", line 579, in get_data
    mod_data_5d = mod_3d.get_data()
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_type.py", line 431, in get_data
    self.file_path[0], self.loader[0], self.dtype[0])
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_type.py", line 510, in _load_single_file
    file_path, loader, dtype)
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_type.py", line 412, in _load_single_file
    image_data = image_obj.get_data()  # new API: get_fdata()
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\dataobj_images.py", line 202, in get_data
    data = np.asanyarray(self._dataobj)
  File "D:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 544, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\arrayproxy.py", line 294, in __array__
    return apply_read_scaling(raw_data, self._slope, self._inter)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\volumeutils.py", line 961, in apply_read_scaling
    ftype = int_scinter_ftype(arr.dtype, slope, inter, default)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\volumeutils.py", line 1209, in int_scinter_ftype
    return _ftype4scaled_finite(tst_arr, slope, inter, 'read', default)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\volumeutils.py", line 1356, in _ftype4scaled_finite
    warnings.filters.pop(0)
IndexError: pop from empty list

originally defined at:
  File ".\net_segment.py", line 8, in <module>
    sys.exit(main())
  File "F:\DLCode\NiftyNet0708\niftynet\__init__.py", line 138, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "F:\DLCode\NiftyNet0708\niftynet\engine\application_driver.py", line 201, in initialise_application
    data_param, app_param, data_partitioner)
  File "F:\DLCode\NiftyNet0708\niftynet\application\segmentation_application.py", line 74, in initialise_dataset_loader
    reader = ImageReader({'image', 'label', 'weight', 'sampler'})
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_reader.py", line 82, in __init__
    super(ImageReader, self).__init__(name='image_reader')
  File "F:\DLCode\NiftyNet0708\niftynet\layer\base_layer.py", line 26, in __init__
    self._op = tf.make_template(name, self.layer_op, create_scope_now_=True)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 153, in make_template
    **kwargs)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "F:\DLCode\NiftyNet0708\niftynet\engine\image_window_buffer.py", line 148, in _push
    for output_dict in self():
  File "F:\DLCode\NiftyNet0708\niftynet\engine\sampler_resize.py", line 73, in layer_op
    image_id, data, interp_orders = self.reader(shuffle=self.shuffle)
  File "F:\DLCode\NiftyNet0708\niftynet\layer\base_layer.py", line 34, in __call__
    return self._op(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 455, in __call__
    result = self._call_func(args, kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 400, in _call_func
    result = self._func(*args, **kwargs)
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_reader.py", line 230, in layer_op
    {field: image.get_data() for (field, image) in image_dict.items()}
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_reader.py", line 230, in <dictcomp>
    {field: image.get_data() for (field, image) in image_dict.items()}
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_type.py", line 579, in get_data
    mod_data_5d = mod_3d.get_data()
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_type.py", line 431, in get_data
    self.file_path[0], self.loader[0], self.dtype[0])
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_type.py", line 510, in _load_single_file
    file_path, loader, dtype)
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_type.py", line 412, in _load_single_file
    image_data = image_obj.get_data()  # new API: get_fdata()
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\dataobj_images.py", line 202, in get_data
    data = np.asanyarray(self._dataobj)
  File "D:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 544, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\arrayproxy.py", line 294, in __array__
    return apply_read_scaling(raw_data, self._slope, self._inter)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\volumeutils.py", line 961, in apply_read_scaling
    ftype = int_scinter_ftype(arr.dtype, slope, inter, default)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\volumeutils.py", line 1209, in int_scinter_ftype
    return _ftype4scaled_finite(tst_arr, slope, inter, 'read', default)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nibabel\volumeutils.py", line 1356, in _ftype4scaled_finite
    warnings.filters.pop(0)
IndexError: pop from empty list

originally defined at:
  File ".\net_segment.py", line 8, in <module>
    sys.exit(main())
  File "F:\DLCode\NiftyNet0708\niftynet\__init__.py", line 138, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "F:\DLCode\NiftyNet0708\niftynet\engine\application_driver.py", line 201, in initialise_application
    data_param, app_param, data_partitioner)
  File "F:\DLCode\NiftyNet0708\niftynet\application\segmentation_application.py", line 74, in initialise_dataset_loader
    reader = ImageReader({'image', 'label', 'weight', 'sampler'})
  File "F:\DLCode\NiftyNet0708\niftynet\io\image_reader.py", line 82, in __init__
    super(ImageReader, self).__init__(name='image_reader')
  File "F:\DLCode\NiftyNet0708\niftynet\layer\base_layer.py", line 26, in __init__
    self._op = tf.make_template(name, self.layer_op, create_scope_now_=True)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 153, in make_template
    **kwargs)


dice: [0.992142856 0.381140113 0.761615515]
dice: [0.982531607 0.921514273 0.795979083]
[1mINFO:niftynet:[0m Training iter 6034, loss=0.1941794753074646 (0.937297s)
[1mINFO:niftynet:[0m Cleaning up...
[1mINFO:niftynet:[0m iter 6034 saved: F:\DLCode\NiftyNet0708\Roi-4M\models\model.ckpt
[1mINFO:niftynet:[0m stopping sampling threads
[1mINFO:niftynet:[0m SegmentationApplication stopped (time in second 34002.00).
PS F:\DLCode\NiftyNet0708>

```

Best regards,
Edward

**Comment by tomvars** [comment]
Hi @EdwardMa12593, can you confirm you've set `num_threads` in your config to a number > 1? I suspect you've run into this issue #https://github.com/nipy/nibabel/issues/616 which I raised a couple of months back and is still open. You can follow my advice from the Github Issue and remove that line, but I would also take the opportunity to post on the issue yourself to show the nibabel devs that this is still ongoing.

**Comment by JunMa11** [comment]
Hi @tomvars, thanks for your advice very much.
You are right, `num_threads = 2` in my config. Following your advice, the problem has been solved.

Best regards,
Edward

**Comment by kanxx030** [comment]
@EdwardMa12593 did you figure out the root cause of this issue? I'm running into the same issue with num_threads =2
