### ISSUE TITLE
batch() missing 1 required positional argument: 'self'    

### ISSUE THREAD

**Issue by snikan-ai** [NifTK/NiftyNet#261]
I want to re-train Deepmedic and HighRes3dNet for comparison (using my own dataset). For both of them I get this error: 

 File …/lib/site-packages/niftynet/engine/image_window_dataset.py, line 238 , in dataset_preprocessing batch() missing 1 required positional argument: 'self'      

 Does anyone have an idea what that means? 

Thanks

**Comment by wyli** [comment]
This can happen when using niftynet 0.4.0 with tensorflow 1.11.0, downgrading TF to v1.10.0 resolves the issue.

**Comment by soodee** [comment]
Thanks Wenqi @wyli .
Downgrading resolved the issue but now I have another error as follows:

[1mINFO:niftynet:[0m Parameters from random initialisations ...
[1mCRITICAL:niftynet:[0m Don't know how to generate sampling locations: Spatial dimensions of the grouped input sources are not consistent. {(538, 644, 579), (115, 132, 121)}
2018-11-06 15:25:57.072420: W c:\users\user\source\repos\tensorflow\tensorflow\core\framework\op_kernel.cc:1263] Unimplemented: NotImplementedError:

originally defined at:
  File "c:\users\soodeh\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\soodeh\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Soodeh\Anaconda3\Scripts\net_segment.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\__init__.py", line 142, in main
    app_driver.run(app_driver.app)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\application_driver.py", line 186, in run
    is_training_action=self.is_training_action)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\application_driver.py", line 249, in create_graph
    application.initialise_sampler()
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\application\segmentation_application.py", line 255, in initialise_sampler
    self.SUPPORTED_SAMPLING[self.net_param.window_sampling][0]()
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\application\segmentation_application.py", line 235, in initialise_balanced_sampler
    self.readers]]
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\application\segmentation_application.py", line 234, in <listcomp>
    queue_length=self.net_param.queue_length) for reader in
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\sampler_balanced_v2.py", line 55, in __init__
    name=name)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\sampler_uniform_v2.py", line 43, in __init__
    name=name)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\image_window_dataset.py", line 61, in __init__
    Layer.__init__(self, name=name)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\layer\base_layer.py", line 26, in __init__
    self._op = tf.make_template(name, self.layer_op, create_scope_now_=True)
  File "c:\users\soodeh\anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)

Traceback (most recent call last):

  File "c:\users\soodeh\anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\image_window_dataset.py", line 297, in <lambda>
    func=lambda subject_id: nest.flatten(self(subject_id)),

  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\layer\base_layer.py", line 34, in __call__
    return self._op(*args, **kwargs)

  File "c:\users\soodeh\anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 359, in __call__
    return self._call_func(args, kwargs)

  File "c:\users\soodeh\anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 310, in _call_func
    result = self._func(*args, **kwargs)

  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\sampler_uniform_v2.py", line 73, in layer_op
    n_samples=self.window.n_samples)

  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\sampler_uniform_v2.py", line 141, in _spatial_coordinates_generator
    _infer_spatial_size(img_sizes, win_sizes)

  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\sampler_uniform_v2.py", line 229, in _infer_spatial_size
    raise NotImplementedError

NotImplementedError:

originally defined at:
  File "c:\users\soodeh\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\soodeh\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Soodeh\Anaconda3\Scripts\net_segment.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\__init__.py", line 142, in main
    app_driver.run(app_driver.app)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\application_driver.py", line 186, in run
    is_training_action=self.is_training_action)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\application_driver.py", line 249, in create_graph
    application.initialise_sampler()
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\application\segmentation_application.py", line 255, in initialise_sampler
    self.SUPPORTED_SAMPLING[self.net_param.window_sampling][0]()
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\application\segmentation_application.py", line 235, in initialise_balanced_sampler
    self.readers]]
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\application\segmentation_application.py", line 234, in <listcomp>
    queue_length=self.net_param.queue_length) for reader in
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\sampler_balanced_v2.py", line 55, in __init__
    name=name)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\sampler_uniform_v2.py", line 43, in __init__
    name=name)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\engine\image_window_dataset.py", line 61, in __init__
    Layer.__init__(self, name=name)
  File "c:\users\soodeh\anaconda3\lib\site-packages\niftynet\layer\base_layer.py", line 26, in __init__
    self._op = tf.make_template(name, self.layer_op, create_scope_now_=True)
  File "c:\users\soodeh\anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)


Any suggestions?

Thanks

**Comment by soodee** [comment]
Anyone's ever had that error?! 
Any guess how to resolve this issue?!

**Comment by mohammad69h94** [comment]
Hi,
I using tf.__version__:  '2.3.0' and python 3.8. but I have the same problem : (TypeError: batch() missing 1 required positional argument: 'self')

What should I do?
