### ISSUE TITLE
raise error when running promise2012 demo

### ISSUE THREAD

**Issue by EdwardMa12593** [NifTK/NiftyNet#31]
I run promise 2012 with the following command
` python net_segment.py train -c demos/PROMISE12/promise12_demo_train_config.ini`
However, following error occurred:
```python
2018-01-23 18:03:38.991667: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
	 [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
2018-01-23 18:03:38.991780: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
	 [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
2018-01-23 18:03:38.991886: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
	 [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
INFO:niftynet: Cleaning up...
INFO:niftynet: iter 142 saved: /home/liver/Documents/Edward/NiftyNet/promise12_model/models/model.ckpt
INFO:niftynet: stopping sampling threads
INFO:niftynet: SegmentationApplication stopped (time in second 491.49).
Traceback (most recent call last):
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
	 [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
	 [[Node: worker_0/loss_function/Mean_2/_141 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3410_worker_0/loss_function/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/__init__.py", line 140, in main
    app_driver.run_application()
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/engine/application_driver.py", line 238, in run_application
    self._training_loop(session, loop_status)
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/engine/application_driver.py", line 432, in _training_loop
    self.run_vars(sess, iter_msg)
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/engine/application_driver.py", line 394, in run_vars
    graph_output = sess.run(vars_to_run, feed_dict=message.data_feed_dict)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
	 [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
	 [[Node: worker_0/loss_function/Mean_2/_141 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3410_worker_0/loss_function/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'worker_0/loss_function/mul', defined at:
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/__init__.py", line 140, in main
    app_driver.run_application()
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/engine/application_driver.py", line 224, in run_application
    self.graph = self._create_graph(self.graph)
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/engine/application_driver.py", line 292, in _create_graph
    self.gradients_collector)
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/application/segmentation_application.py", line 281, in connect_data_and_network
    weight_map=data_dict.get('weight', None))
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/layer/base_layer.py", line 34, in __call__
    return self._op(*args, **kwargs)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 268, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/layer/loss_segmentation.py", line 113, in layer_op
    loss_batch.append(self._data_loss_func(**loss_params))
  File "/home/liver/Documents/Edward/NiftyNet/niftynet/layer/loss_segmentation.py", line 410, in dice
    one_hot * prediction, reduction_axes=[0])
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 905, in binary_op_wrapper_sparse
    name=name), sp_x.dense_shape)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_sparse_ops.py", line 852, in sparse_dense_cwise_mul
    sp_shape=sp_shape, dense=dense, name=name)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/liver/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
	 [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
	 [[Node: worker_0/loss_function/Mean_2/_141 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3410_worker_0/loss_function/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```
would it be possible for you to tell me how to solve this problem.\
Looking forward to your reply.
Best wishes,
Edward

**Comment by wyli** [comment]
Hi @EdwardMa12593  many thanks for the feedback, this looks the same as https://github.com/NifTK/NiftyNet/issues/8; 
It's now fixed in `dev`: https://github.com/NifTK/NiftyNet/commit/8bd9ac6045cae4df0e8e71b78d9e5fda4bfe48fd.
Please feel free to reopen if the problem persists.

**Comment by EdwardMa12593** [comment]
Hi,  @wyli , thanks for your quick reply. The training is now working without errors.
I have one more question about the data loading module. In promise2012 demo, how the input data (.mhd files in [PROMISE12](https://github.com/NifTK/NiftyNet/tree/dev/data/PROMISE12)) is imported into the network?
I know the niftynet defines the [load_image(filename) function](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/io/misc_io.py) in `niftynet/io/misc_io.py`. However, I don't find how the `load_image` is called in promise 2012 demo.
there is no `load_image` function in both [application_driver.py](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/engine/application_driver.py) and [segmentation_application.py](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/application/segmentation_application.py).

Looking forward to your reply.
Best wishes,
Edward
