### ISSUE TITLE
How Do I Run a Simple GAN without any conditioning?

### ISSUE THREAD

**Issue by enochkan** [NifTK/NiftyNet#330]
How Do I Run a Simple GAN without any conditioning?

I have downloaded the source code and ran net_gan, which uses gan_application.py and obtained the following error:

CRITICAL:niftynet: Reader requires task input keywords ('conditioning',), but not exist in the config file.
Available task keywords: ['noise_size', 'image', 'n_interpolations', 'conditioning', 'name']
Traceback (most recent call last):
  File "net_gan.py", line 8, in <module>
    sys.exit(main())
  File "/Users/kan7792/NiftyNet/niftynet/__init__.py", line 141, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "/Users/kan7792/NiftyNet/niftynet/engine/application_driver.py", line 167, in initialise_application
    data_param, app_param, self.data_partitioner)
  File "/Users/kan7792/NiftyNet/niftynet/application/gan_application.py", line 69, in initialise_dataset_loader
    data_param, task_param, file_list) for file_list in file_lists]
  File "/Users/kan7792/NiftyNet/niftynet/io/image_reader.py", line 142, in initialise
    raise ValueError
ValueError

It makes perfect sense because it is looking for a conditioning field in my config, which does not exist because I'm using the generic gan (simple_gan.py) without any conditioning.

**Comment by carlpe** [comment]
Did you find out how to do it, chinokenochkan?

**Comment by enochkan** [comment]
@carlpe my apologies for the late reply. I've switched to other source codes (not niftynet) for simple gan.

**Comment by carlpe** [comment]
@chinokenochkan 
May I ask which one you have been most successful?
