### ISSUE TITLE
fine tuning

### ISSUE THREAD

**Issue by VanitarNordic** [NifTK/NiftyNet#37]
Hi,

is it possible to fine-tune the model on a custom dataset?

**Comment by CourantNg** [comment]
A similar question. 
I have  trained a model in promise2012 dataset, whether can I use this trained model as an initialization on other dataset (such as left ventricle MR/CT dataset).

**Comment by eligibson** [comment]
If you want to fine tune the model on a different dataset, you can do that without any coding by naming the model checkpoints accordingly. 
1) Copy the trained model to 
MODEL_DIR/models/model.ckpt-1.*
2) Copy the config file and change the model_dir to MODEL_DIR, the starting_iter to 1 in the config file, and the data entries to point to your new data.

There are other ways to do this in code using the restore_from_checkpoint method, if you need finer grained control of what is restored from the checkpoint.

**Comment by tvercaut** [comment]
Thanks @eligibson, this is probably something we should put in the howto guides on readthedocs:
http://niftynet.readthedocs.io/en/dev/index.html#guides

**Comment by AkhilaPerumalla123** [comment]
> If you want to fine tune the model on a different dataset, you can do that without any coding by naming the model checkpoints accordingly.
> 
> 1. Copy the trained model to
>    MODEL_DIR/models/model.ckpt-1.*
> 2. Copy the config file and change the model_dir to MODEL_DIR, the starting_iter to 1 in the config file, and the data entries to point to your new data.
> 
> There are other ways to do this in code using the restore_from_checkpoint method, if you need finer grained control of what is restored from the checkpoint.

I am getting below error

**INFO:niftynet: stopping sampling threads
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,61,256] rhs shape= [3,3,3,61,9]
         [[{{node save/Assign_19}} = Assign[T=DT_FLOAT, _class=["loc:@DenseVNet/conv/conv_/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DenseVNet/conv/conv_/w/Adam_1, save/RestoreV2/_39)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1546, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,61,256] rhs shape= [3,3,3,61,9]
         [[node save/Assign_19 (defined at /home/NiftyNet/niftynet/engine/handler_model.py:109)  = Assign[T=DT_FLOAT, _class=["loc:@DenseVNet/conv/conv_/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DenseVNet/conv/conv_/w/Adam_1, save/RestoreV2/_39)]]

Caused by op 'save/Assign_19', defined at:
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "/home/NiftyNet/niftynet/__init__.py", line 142, in main
    app_driver.run(app_driver.app)
  File "/home/NiftyNet/niftynet/engine/application_driver.py", line 197, in run
    SESS_STARTED.send(application, iter_msg=None)
  File "/usr/local/lib/python3.5/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/NiftyNet/niftynet/engine/handler_model.py", line 109, in restore_model
    var_list=to_restore, save_relative_paths=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,61,256] rhs shape= [3,3,3,61,9]
         [[node save/Assign_19 (defined at /home/NiftyNet/niftynet/engine/handler_model.py:109)  = Assign[T=DT_FLOAT, _class=["loc:@DenseVNet/conv/conv_/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DenseVNet/conv/conv_/w/Adam_1, save/RestoreV2/_39)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "/home/NiftyNet/niftynet/__init__.py", line 142, in main
    app_driver.run(app_driver.app)
  File "/home/NiftyNet/niftynet/engine/application_driver.py", line 197, in run
    SESS_STARTED.send(application, iter_msg=None)
  File "/usr/local/lib/python3.5/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/NiftyNet/niftynet/engine/handler_model.py", line 110, in restore_model
    saver.restore(tf.get_default_session(), checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1582, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,61,256] rhs shape= [3,3,3,61,9]
         [[node save/Assign_19 (defined at /home/NiftyNet/niftynet/engine/handler_model.py:109)  = Assign[T=DT_FLOAT, _class=["loc:@DenseVNet/conv/conv_/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DenseVNet/conv/conv_/w/Adam_1, save/RestoreV2/_39)]]

Caused by op 'save/Assign_19', defined at:
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "/home/NiftyNet/niftynet/__init__.py", line 142, in main
    app_driver.run(app_driver.app)
  File "/home/NiftyNet/niftynet/engine/application_driver.py", line 197, in run
    SESS_STARTED.send(application, iter_msg=None)
  File "/usr/local/lib/python3.5/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/NiftyNet/niftynet/engine/handler_model.py", line 109, in restore_model
    var_list=to_restore, save_relative_paths=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,61,256] rhs shape= [3,3,3,61,9]
         [[node save/Assign_19 (defined at /home/NiftyNet/niftynet/engine/handler_model.py:109)  = Assign[T=DT_FLOAT, _class=["loc:@DenseVNet/conv/conv_/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DenseVNet/conv/conv_/w/Adam_1, save/RestoreV2/_39)]]
**

**Comment by ericspod** [comment]
This appears to be caused by creating a network based on data with a different dimensionality than the one being loaded from the checkpoint. If you want to train on a 2D dataset the weights of some convolution would have a 4D dimension (ie. shape= [3,3,61,256])  whereas those being loaded from the zoo would have 5D (ie. shape= [3,3,3,61,9]).

**Comment by koriavinash1** [comment]
@ericspod  Is it possible to add new layers in between and fine-tune the model on a custom dataset?

**Comment by ericspod** [comment]
@koriavinash1 I'm afraid not, at least not trivially. The models are loaded from the zoo as checkpoints so you can't really have a different model with new layers load data from that.
