### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by CourantNg** [NifTK/NiftyNet#41]
When the segmentation training beginning, following error occurred
`TypeError: not all arguments converted during string formatting`
Following is the full error information.

```python
Number of subjects 1432, input section names: ['subject_id', 'Liver2018', 'Liverlabel']
Dataset partitioning:
-- Training 1360 cases (94.97%),
-- Validation 36 cases (2.51%),
-- Inference 36 cases (2.51%).

initialise readers in application_driver
[1mINFO:niftynet:[0m Image reader: loading [image] from ('Liver2018',) (1360)
[1mINFO:niftynet:[0m Image reader: loading [label] from ('Liverlabel',) (1360)
[1mINFO:niftynet:[0m Image reader: loading [image] from ('Liver2018',) (36)
[1mINFO:niftynet:[0m Image reader: loading [label] from ('Liverlabel',) (36)
[1mINFO:niftynet:[0m reading size of preprocessed images (in sampler_resize.py)
sampler_resize中spatial_window_size =  ()
[1mINFO:niftynet:[0m initialised window instance
[1mINFO:niftynet:[0m buffering with 3 windows
--- Logging error ---
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "E:\Yang\niftynet\__init__.py", line 129, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "E:\Yang\niftynet\engine\application_driver.py", line 192, in initialise_application
    self.app.initialise_sampler()
  File "E:\Yang\niftynet\application\segmentation_application.py", line 212, in initialise_sampler
    self.SUPPORTED_SAMPLING[self.net_param.window_sampling][0]()
  File "E:\Yang\niftynet\application\segmentation_application.py", line 184, in initialise_resize_sampler
    self.readers]]
  File "E:\Yang\niftynet\application\segmentation_application.py", line 183, in <listcomp>
    queue_length=self.net_param.queue_length) for reader in
  File "E:\Yang\niftynet\engine\sampler_resize.py", line 60, in __init__
    " [-1 for dynamic size]", self.window.shapes, "(in sampler_resize.py)")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\tf_logging.py", line 82, in info
    _logger.info(msg, *args, **kwargs)
Message: 'initialised sampler output %s  [-1 for dynamic size]'
Arguments: ({'image': (128, 128, 64, 1, 1), 'label': (128, 128, 64, 1, 1)}, '(in sampler_resize.py)')
--- Logging error ---
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "E:\Yang\niftynet\__init__.py", line 129, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "E:\Yang\niftynet\engine\application_driver.py", line 192, in initialise_application
    self.app.initialise_sampler()
  File "E:\Yang\niftynet\application\segmentation_application.py", line 212, in initialise_sampler
    self.SUPPORTED_SAMPLING[self.net_param.window_sampling][0]()
  File "E:\Yang\niftynet\application\segmentation_application.py", line 184, in initialise_resize_sampler
    self.readers]]
  File "E:\Yang\niftynet\application\segmentation_application.py", line 183, in <listcomp>
    queue_length=self.net_param.queue_length) for reader in
  File "E:\Yang\niftynet\engine\sampler_resize.py", line 60, in __init__
    " [-1 for dynamic size]", self.window.shapes, "(in sampler_resize.py)")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\tf_logging.py", line 82, in info
    _logger.info(msg, *args, **kwargs)
Message: 'initialised sampler output %s  [-1 for dynamic size]'
Arguments: ({'image': (128, 128, 64, 1, 1), 'label': (128, 128, 64, 1, 1)}, '(in sampler_resize.py)')
[1mINFO:niftynet:[0m reading size of preprocessed images (in sampler_resize.py)
sampler_resize中spatial_window_size =  ()
[1mINFO:niftynet:[0m initialised window instance
[1mINFO:niftynet:[0m buffering with 3 windows
--- Logging error ---
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "E:\Yang\niftynet\__init__.py", line 129, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "E:\Yang\niftynet\engine\application_driver.py", line 192, in initialise_application
    self.app.initialise_sampler()
  File "E:\Yang\niftynet\application\segmentation_application.py", line 212, in initialise_sampler
    self.SUPPORTED_SAMPLING[self.net_param.window_sampling][0]()
  File "E:\Yang\niftynet\application\segmentation_application.py", line 184, in initialise_resize_sampler
    self.readers]]
  File "E:\Yang\niftynet\application\segmentation_application.py", line 183, in <listcomp>
    queue_length=self.net_param.queue_length) for reader in
  File "E:\Yang\niftynet\engine\sampler_resize.py", line 60, in __init__
    " [-1 for dynamic size]", self.window.shapes, "(in sampler_resize.py)")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\tf_logging.py", line 82, in info
    _logger.info(msg, *args, **kwargs)
Message: 'initialised sampler output %s  [-1 for dynamic size]'
Arguments: ({'image': (128, 128, 64, 1, 1), 'label': (128, 128, 64, 1, 1)}, '(in sampler_resize.py)')
--- Logging error ---
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "E:\Yang\niftynet\__init__.py", line 129, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "E:\Yang\niftynet\engine\application_driver.py", line 192, in initialise_application
    self.app.initialise_sampler()
  File "E:\Yang\niftynet\application\segmentation_application.py", line 212, in initialise_sampler
    self.SUPPORTED_SAMPLING[self.net_param.window_sampling][0]()
  File "E:\Yang\niftynet\application\segmentation_application.py", line 184, in initialise_resize_sampler
    self.readers]]
  File "E:\Yang\niftynet\application\segmentation_application.py", line 183, in <listcomp>
    queue_length=self.net_param.queue_length) for reader in
  File "E:\Yang\niftynet\engine\sampler_resize.py", line 60, in __init__
    " [-1 for dynamic size]", self.window.shapes, "(in sampler_resize.py)")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\tf_logging.py", line 82, in info
    _logger.info(msg, *args, **kwargs)
Message: 'initialised sampler output %s  [-1 for dynamic size]'
Arguments: ({'image': (128, 128, 64, 1, 1), 'label': (128, 128, 64, 1, 1)}, '(in sampler_resize.py)')

2018-01-30 12:06:06.306439: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions,
 but these are available on your machine and could speed up CPU computations.
2018-01-30 12:06:06.306439: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions
, but these are available on your machine and could speed up CPU computations.
2018-01-30 12:06:06.551453: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.683
pciBusID 0000:01:00.0
Total memory: 11.00GiB
Free memory: 10.58GiB

```

**Comment by wyli** [comment]
Hi @CourantNg for some reason the string `(in sampler_resize.py)` is parsed from the config file as a user parameter, could you please post the relevant config file section?

**Comment by CourantNg** [comment]
Thanks for your quick reply. Following is my config.
```python
[image]
path_to_search = 
filename_contains = volume
filename_not_contains = segmentation
spatial_window_size = (128, 128, 64)
interp_order = 1
axcodes=(A, R, S)

[label]
path_to_search = 
filename_contains = segmentation
filename_not_contains = volume
spatial_window_size = (128, 128, 64)
interp_order = 0
axcodes=(A, R, S)

############################## system configuration sections
[SYSTEM]
cuda_devices = ""
num_threads = 2
num_gpus = 1
model_dir = 

[NETWORK]
name = vnet
activation_function = prelu
batch_size = 2

# volume level preprocessing
volume_padding_size = 0
window_sampling = resize
normalisation = False
whitening = False

queue_length = 6


[TRAINING]
sample_per_volume = 4
lr = 0.00002
loss_type = Dice
starting_iter = 0
save_every_n = 400
max_iter = 10001
max_checkpoints = 20
tensorboard_every_n = 10

validation_every_n = 50
exclude_fraction_for_validation = 0.025
exclude_fraction_for_inference = 0.025

[INFERENCE]
border = (5, 5, 5)
save_seg_dir = 
output_interp_order = 0
spatial_window_size = (0, 0, 3)


############################ custom configuration sections
[SEGMENTATION]
image = image
label = label
output_prob = False
num_classes = 2
label_normalisation = True
min_numb_labels = 2
min_sampling_ratio = 0.000001

```

**Comment by wyli** [comment]
This bit is suspicious, , was it added for debugging?
```
E:\Yang\niftynet\engine\sampler_resize.py", line 60, in __init__
    " [-1 for dynamic size]", self.window.shapes, "(in sampler_resize.py)")
```
removing `, "(in sampler_resize.py)"` should work.

**Comment by CourantNg** [comment]
Dear @wyli 
You are right.
Thank you very much for your time and help.
