### ISSUE TITLE
Error in 'window_sampling'

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#85]
Hi, I had this error after changing the 'uniform' to 'balanced' for [window_sampling]. 

`INFO:niftynet: Import [Adam] from /home/yilinliu/Niftynet/niftynet/engine/application_optimiser.pyc.
INFO:niftynet: Import [cross_entropy] from /home/yilinliu/Niftynet/niftynet/layer/loss_segmentation.pyc.
INFO:niftynet: Cross entropy loss function calls tf.nn.sparse_softmax_cross_entropy_with_logits which always performs a softmax internally.
INFO:niftynet: starting from iter 0
INFO:niftynet: Parameters from random initialisations ...
Traceback (most recent call last):
  File "/home/yilinliu/Niftynet/niftynet/engine/image_window_buffer.py", line 143, in _push
    for output_dict in self():
  File "/home/yilinliu/Niftynet/niftynet/engine/sampler_uniform.py", line 79, in layer_op
    self.window.n_samples)
  File "/home/yilinliu/Niftynet/niftynet/engine/sampler_uniform.py", line 157, in _spatial_coordinates_generator
    n_samples, img_spatial_size, win_spatial_size, sampling_prior_map)
  File "/home/yilinliu/Niftynet/niftynet/engine/sampler_balanced.py", line 76, in balanced_spatial_coordinates
    sampler_map.shape[:N_SPATIAL]), \
AttributeError: 'NoneType' object has no attribute 'shape'`

I very much hope to use this function to relieviate the imbalanced class problem in my case. My ROIs are some very small brain structures. 

Thanks!!

**Comment by wyli** [comment]
please see #86
